### ISSUE TITLE
Conflicts with libvirt

### ISSUE THREAD

**Issue by jgammon612** [rafaeltuelho/jboss-eap-managed-on-docker#3]
docker-compose up
Creating jbosseapmanagedondocker_dnsmasq_1...
Cannot start container ce1172a905613bf00901d1e66a1f03acecc9282f4f57a2453b51acbee0165537: Error starting userland proxy: listen udp 0.0.0.0:53: bind: address already in use

Did a netstat -na
[jgammon612@jgammon612 jboss-eap-managed-on-docker]$ netstat -na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State  
tcp        0      0 127.0.0.1:50472         0.0.0.0:\*               LISTEN  
tcp        0      0 127.0.0.1:1194          0.0.0.0:\*               LISTEN  
tcp        0      0 127.0.0.1:58957         0.0.0.0:\*               LISTEN  
tcp        0      0 192.168.100.1:53        0.0.0.0:\*               LISTEN  
tcp        0      0 10.10.10.1:53           0.0.0.0:\*               LISTEN  
tcp        0      0 0.0.0.0:22              0.0.0.0:\*               LISTEN  
tcp        0      0 127.0.0.1:631           0.0.0.0:\*               LISTEN  
tcp        0      0 127.0.0.1:25            0.0.0.0:\*               LISTEN  
tcp        0      0 127.0.0.1:38654         0.0.0.0:\*               LISTEN  
tcp        0      0 192.168.1.80:50879      23.235.39.133:443       ESTABLISHED
tcp        0      0 192.168.1.80:50880      23.235.39.133:443       ESTABLISHED
tcp        0      0 127.0.0.1:1194          127.0.0.1:53889         ESTABLISHED
tcp        0      0 192.168.1.80:52732      192.30.252.129:443      TIME_WAIT  
tcp        0      0 192.168.1.80:51161      199.48.152.168:5000     ESTABLISHED
tcp        0      0 192.168.1.80:50877      23.235.39.133:443       ESTABLISHED
tcp        0      0 192.168.1.80:43276      192.30.252.87:443       ESTABLISHED
tcp        0      0 192.168.1.80:50878      23.235.39.133:443       ESTABLISHED
tcp        0      0 192.168.1.80:38609      192.30.252.88:443       ESTABLISHED
tcp        0    679 192.168.1.80:48674      209.132.183.3:443       ESTABLISHED
tcp        0      0 192.168.1.80:56464      192.30.252.91:443       ESTABLISHED
tcp        0      0 192.168.1.80:58677      107.23.78.89:443        ESTABLISHED
tcp        0      0 192.168.1.80:46742      199.48.152.165:443      ESTABLISHED
tcp        0      0 192.168.1.80:37596      192.30.252.124:443      TIME_WAIT  
tcp        0      0 192.168.1.80:56388      192.30.252.91:443       ESTABLISHED
tcp        0      0 192.168.1.80:38037      192.30.252.88:443       ESTABLISHED
tcp        0      0 192.168.1.80:50881      23.235.39.133:443       ESTABLISHED
tcp        0      0 192.168.1.80:48376      52.26.119.85:443        ESTABLISHED
tcp        0      0 192.168.1.80:39435      199.27.79.133:443       ESTABLISHED
tcp        0      0 192.168.1.80:39214      199.48.152.140:443      ESTABLISHED
tcp        0      0 192.168.1.80:39434      199.27.79.133:443       ESTABLISHED
tcp        0    572 10.3.112.68:45426       10.4.122.7:389          ESTABLISHED
tcp        0      0 127.0.0.1:53889         127.0.0.1:1194          ESTABLISHED
tcp6       0      0 :::22                   :::\*                    LISTEN  
tcp6       0      0 ::1:631                 :::\*                    LISTEN  
tcp6       0      0 ::1:25                  :::\*                    LISTEN  
tcp6       0      0 2602:304:b130:4cf:49759 2607:f8b0:4010:800::443 ESTABLISHED
tcp6       0      0 2602:304:b130:4cf:43911 2607:f8b0:4010:800::443 ESTABLISHED
tcp6       0      0 2602:304:b130:4cf:33105 2607:f8b0:4005:802::443 ESTABLISHED
tcp6       0      0 2602:304:b130:4cf:45459 2607:f8b0:4002:c06::443 ESTABLISHED
tcp6       0      0 2602:304:b130:4cf:49123 2607:f8b0:4010:800::443 ESTABLISHED
udp        0      0 0.0.0.0:5866            0.0.0.0:\*  
udp        0      0 0.0.0.0:5922            0.0.0.0:\*  
udp        0      0 192.168.100.1:53        0.0.0.0:\*  
udp        0      0 10.10.10.1:53           0.0.0.0:\*  
udp        0      0 0.0.0.0:67              0.0.0.0:\*  
udp        0      0 0.0.0.0:67              0.0.0.0:\*  
udp        0      0 0.0.0.0:68              0.0.0.0:\*  
udp        0      0 127.0.0.1:323           0.0.0.0:\*  
udp        0      0 0.0.0.0:1455            0.0.0.0:\*  
udp        0      0 0.0.0.0:35954           0.0.0.0:\*  
udp        0      0 0.0.0.0:5353            0.0.0.0:\*  
udp6       0      0 ::1:323                 :::\*  
udp6       0      0 :::43625                :::\*  
raw6       0      0 :::58                   :::\*                    7  
raw6       0      0 :::58                   :::\*                    7

**Comment by rafaeltuelho** [comment]
Thanks!

I fixed in last commit. Now the dnsmasq service will use the `docker0` (`172.17.42.1`) net ifc.

**Comment by jgammon612** [comment]
sorry to ask but how do I pull the latest? Do I do a git clone and rebuild?

John

----- Original Message -----

**Comment by rafaeltuelho** [comment]
Do

`git pull`

to get update your local repo.

**Comment by jgammon612** [comment]
SAME ERROR:

 git pull
Updating 3031594..a2525c8
Fast-forward
 docker-compose.yml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

Removing jbosseapmanagedondocker_dnsmasq_1...
Recreating ce1172a905_ce1172a905_jbosseapmanagedondocker_dnsmasq_1...
Cannot start container 65a1890007b74594be199caef2ac5bc1a5753f0422d6245bc6612229bcdc230c: iptables failed: iptables --wait -t nat -A DOCKER -p udp -d 172.17.42.1 --dport 53 -j DNAT --to-destination 172.17.0.7:53 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)

----- Original Message -----

**Comment by rafaeltuelho** [comment]
Hum! I did not see this issue on my environment. I used a RHEL 7 box to implement this setup. The only thing I did is to put the SELinux in Permissive mode.
