### ISSUE TITLE
Environment builds and Runs and Apps Available but no Clustered domain

### ISSUE THREAD

**Issue by jgammon612** [rafaeltuelho/jboss-eap-managed-on-docker#4]
Upon attempt to discover CLustered EAP domain -- nothing shows in discovery queue except jon server which I imported
![mod_cluster](https://cloud.githubusercontent.com/assets/14928349/10321246/4660026c-6c3d-11e5-8430-65e945570c2e.png)
![eap_domain_empty](https://cloud.githubusercontent.com/assets/14928349/10321251/4a98ab72-6c3d-11e5-8888-8de94efe44e6.png)

**Comment by jgammon612** [comment]
![jon discovery queue](https://cloud.githubusercontent.com/assets/14928349/10321315/8d776cda-6c3d-11e5-91b4-50275ac0937d.png)

![dockerps](https://cloud.githubusercontent.com/assets/14928349/10321346/c7c8c712-6c3d-11e5-8cab-a3662f7947d4.png)

**Comment by jgammon612** [comment]
![dockerps](https://cloud.githubusercontent.com/assets/14928349/10321366/de856064-6c3d-11e5-95bc-d393b0053cc9.png)

**Comment by jgammon612** [comment]
![docker_ps](https://cloud.githubusercontent.com/assets/14928349/10321406/1305ab46-6c3e-11e5-8ca4-f94e9bfebc86.png)

**Comment by rafaeltuelho** [comment]
@jgammon612, I can't see the EAP containers in this last screenshot (`docker ps`).

How many GB of RAM do you have available in your host where the docker is running. 
Your host is a Fedora or RHEL box?

Try the `docker-compose logs > compose.out`. Put the result in a `pastebin` and share with me. I have to see the logs to find the issue.

**Comment by jgammon612** [comment]
plenty of RAM -- 16GB -- did you get compose.out from email?

**Comment by jgammon612** [comment]
RHEL7

**Comment by rafaeltuelho** [comment]
put the log output in a gist: https://gist.github.com/

**Comment by jgammon612** [comment]
https://gist.github.com/jgammon612/208964a772aa31991155

**Comment by rafaeltuelho** [comment]
Looking in the log it appears the EAP slaves can't talk/resolv the master address. But I don't know why :-/

can you run the cmd 
`sudo iptables -L` in your host?

can you see something like that?

```
Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             dnsmasq.docker.local  udp dpt:domain
ACCEPT     tcp  --  anywhere             master.docker.local  tcp dpt:distinct
ACCEPT     tcp  --  anywhere             master.docker.local  tcp dpt:osm-appsrvr
ACCEPT     tcp  --  anywhere             apache.docker.local  tcp dpt:ircu-2
ACCEPT     tcp  --  anywhere             apache.docker.local  tcp dpt:http
ACCEPT     tcp  --  anywhere             jon-server.docker.local  tcp dpt:empowerid

```

**Comment by rafaeltuelho** [comment]
I'm guessing the problem have to do with containers' startup ordering. Docker Compose is starting the EAPs before the dnsmasq. I changed the `docker-compose.yml` to fix this. Can you please update your local repo (`git pull`) and run `docker-compose up` again?

**Comment by jgammon612** [comment]
git pull complete

[root@jgammon612 jgammon612]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination  
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere  
ACCEPT     all  --  anywhere             anywhere  
ACCEPT     tcp  --  anywhere             anywhere             state NEW tcp dpt:ssh
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination  
DOCKER     all  --  anywhere             anywhere  
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere  
ACCEPT     all  --  anywhere             anywhere  
ACCEPT     all  --  anywhere             192.168.100.0/24     ctstate RELATED,ESTABLISHED
ACCEPT     all  --  192.168.100.0/24     anywhere  
ACCEPT     all  --  anywhere             anywhere  
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
ACCEPT     all  --  anywhere             10.10.10.0/24  
ACCEPT     all  --  10.10.10.0/24        anywhere  
ACCEPT     all  --  anywhere             anywhere  
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination  
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc

Chain DOCKER (1 references)
target     prot opt source               destination  
ACCEPT     udp  --  anywhere             dnsmasq.docker.local  udp dpt:domain
ACCEPT     tcp  --  anywhere             172.17.0.6           tcp dpt:distinct
ACCEPT     tcp  --  anywhere             172.17.0.6           tcp dpt:osm-appsrvr
ACCEPT     tcp  --  anywhere             172.17.0.9           tcp dpt:ircu-2
ACCEPT     tcp  --  anywhere             172.17.0.9           tcp dpt:http
ACCEPT     tcp  --  anywhere             172.17.0.11          tcp dpt:empowerid

**Comment by jgammon612** [comment]
results after git pull

eapslave1_1   | starting RHQ Agent service...
eapslave1_1   | rhq-agent-wrapper.sh: RHQ_AGENT_WRAPPER_BIN_DIR_PATH=/opt/redhat/rhq-agent/bin
eapslave1_1   | rhq-agent-wrapper.sh: Loading environment script: /opt/redhat/rhq-agent/bin/rhq-agent-env.sh
eapslave1_1   | rhq-agent-wrapper.sh: pidfile will be located at /opt/redhat/rhq-agent/bin/rhq-agent.pid
eapslave1_1   | Starting RHQ Agent...
eapslave1_1   | rhq-agent-wrapper.sh: Start script found here: /opt/redhat/rhq-agent/bin/rhq-agent.sh
eapslave1_1   | rhq-agent-wrapper.sh: Executing agent with command: '/opt/redhat/rhq-agent/bin/rhq-agent.sh'
eapslave1_1   | =========================================================================
eapslave1_1   | 
eapslave1_1   |   JBoss Bootstrap Environment
eapslave1_1   | 
eapslave1_1   |   JBOSS_HOME: /opt/redhat/jboss-eap-6.4
eapslave1_1   | 
eapslave1_1   |   JAVA: /usr/lib/jvm/java/bin/java
eapslave1_1   | 
eapslave1_1   |   JAVA_OPTS: -server -Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Djboss.modules.policy-permissions=true
eapslave1_1   | 
eapslave1_1   | =========================================================================
eapslave1_1   | 
eapslave1_1   | 23:33:39,916 INFO  [org.jboss.modules](main) JBoss Modules version 1.3.6.Final-redhat-1
eapslave1_1   | 23:33:40,005 INFO  [org.jboss.as.process.Host Controller.status](main) JBAS012017: Starting process 'Host Controller'
eapslave1_1   | [Host Controller] 23:33:40,318 INFO  [org.jboss.modules](main) JBoss Modules version 1.3.6.Final-redhat-1
eapslave2_1   | starting RHQ Agent service...
eapslave2_1   | rhq-agent-wrapper.sh: RHQ_AGENT_WRAPPER_BIN_DIR_PATH=/opt/redhat/rhq-agent/bin
eapslave2_1   | rhq-agent-wrapper.sh: Loading environment script: /opt/redhat/rhq-agent/bin/rhq-agent-env.sh
eapslave1_1   | [Host Controller] 23:33:40,408 INFO  [org.jboss.msc](main) JBoss MSC version 1.1.5.Final-redhat-1
eapslave2_1   | rhq-agent-wrapper.sh: pidfile will be located at /opt/redhat/rhq-agent/bin/rhq-agent.pid
eapslave2_1   | Starting RHQ Agent...
eapslave2_1   | rhq-agent-wrapper.sh: Start script found here: /opt/redhat/rhq-agent/bin/rhq-agent.sh
eapslave2_1   | rhq-agent-wrapper.sh: Executing agent with command: '/opt/redhat/rhq-agent/bin/rhq-agent.sh'
eapslave1_1   | [Host Controller] 23:33:40,442 INFO  [org.jboss.as](MSC service thread 1-7) JBAS015899: JBoss EAP 6.4.2.GA (AS 7.5.2.Final-redhat-2) starting
eapslave2_1   | =========================================================================
eapslave2_1   | 
eapslave2_1   |   JBoss Bootstrap Environment
eapslave2_1   | 
eapslave2_1   |   JBOSS_HOME: /opt/redhat/jboss-eap-6.4
eapslave2_1   | 
eapslave2_1   |   JAVA: /usr/lib/jvm/java/bin/java
eapslave2_1   | 
eapslave2_1   |   JAVA_OPTS: -server -Xms64m -Xmx512m -XX:MaxPermSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Djboss.modules.policy-permissions=true
eapslave2_1   | 
eapslave2_1   | =========================================================================
eapslave2_1   | 
eapslave2_1   | 23:33:40,881 INFO  [org.jboss.modules](main) JBoss Modules version 1.3.6.Final-redhat-1
eapslave1_1   | [Host Controller] 23:33:40,966 INFO  [org.xnio](MSC service thread 1-13) XNIO Version 3.0.14.GA-redhat-1
eapslave1_1   | [Host Controller] 23:33:40,969 INFO  [org.xnio.nio](MSC service thread 1-13) XNIO NIO Implementation Version 3.0.14.GA-redhat-1
eapslave1_1   | [Host Controller] 23:33:40,982 INFO  [org.jboss.as](Controller Boot Thread) JBAS010902: Creating http management service using network interface (management) port (9990) securePort (-1)
eapslave1_1   | [Host Controller] 23:33:40,996 INFO  [org.jboss.remoting](MSC service thread 1-13) JBoss Remoting version 3.3.5.Final-redhat-1
eapslave2_1   | 23:33:41,001 INFO  [org.jboss.as.process.Host Controller.status](main) JBAS012017: Starting process 'Host Controller'
eapslave1_1   | [Host Controller] 23:33:41,027 INFO  [org.jboss.as.remoting](MSC service thread 1-6) JBAS017100: Listening on 0.0.0.0:9999
eapslave1_1   | [Host Controller] 23:33:41,233 WARN  [org.jboss.as.host.controller](Controller Boot Thread) JBAS010900: Could not connect to remote domain controller at remote://master:9999 -- java.nio.channels.UnresolvedAddressException
eapslave1_1   | [Host Controller] 23:33:41,233 WARN  [org.jboss.as.host.controller](Controller Boot Thread) JBAS016581: No domain controller discovery options remain.
eapslave1_1   | [Host Controller] 23:33:41,237 ERROR [org.jboss.as.host.controller](Controller Boot Thread) JBAS010901: Could not connect to master. Aborting. Error was: java.lang.IllegalStateException: JBAS016519: Tried all domain controller discovery option(s) but unable to connect
eapslave1_1   | [Host Controller] 23:33:41,251 INFO  [org.jboss.as](MSC service thread 1-13) JBAS015950: JBoss EAP 6.4.2.GA (AS 7.5.2.Final-redhat-2) stopped in 12ms
eapslave2_1   | [Host Controller] 23:33:41,389 INFO  [org.jboss.modules](main) JBoss Modules version 1.3.6.Final-redhat-1
eapslave2_1   | [Host Controller] 23:33:41,474 INFO  [org.jboss.msc](main) JBoss MSC version 1.1.5.Final-redhat-1
eapslave2_1   | [Host Controller] 23:33:41,518 INFO  [org.jboss.as](MSC service thread 1-7) JBAS015899: JBoss EAP 6.4.2.GA (AS 7.5.2.Final-redhat-2) starting
eapslave1_1   | [Host Controller] 
eapslave1_1   | 23:33:41,573 INFO  [org.jboss.as.process.Host Controller.status](reaper for Host Controller) JBAS012010: Process 'Host Controller' finished with an exit status of 99
eapslave1_1   | 23:33:41,575 INFO  [org.jboss.as.process](Thread-8) JBAS012016: Shutting down process controller
eapslave1_1   | 23:33:41,575 INFO  [org.jboss.as.process](Thread-8) JBAS012015: All processes finished; exiting
eapslave2_1   | [Host Controller] 23:33:41,915 INFO  [org.xnio](MSC service thread 1-5) XNIO Version 3.0.14.GA-redhat-1
eapslave2_1   | [Host Controller] 23:33:41,918 INFO  [org.xnio.nio](MSC service thread 1-5) XNIO NIO Implementation Version 3.0.14.GA-redhat-1
eapslave2_1   | [Host Controller] 23:33:41,919 INFO  [org.jboss.as](Controller Boot Thread) JBAS010902: Creating http management service using network interface (management) port (9990) securePort (-1)
eapslave2_1   | [Host Controller] 23:33:41,929 INFO  [org.jboss.remoting](MSC service thread 1-5) JBoss Remoting version 3.3.5.Final-redhat-1
eapslave2_1   | [Host Controller] 23:33:41,948 INFO  [org.jboss.as.remoting](MSC service thread 1-4) JBAS017100: Listening on 0.0.0.0:9999
eapslave2_1   | [Host Controller] 23:33:42,086 WARN  [org.jboss.as.host.controller](Controller Boot Thread) JBAS010900: Could not connect to remote domain controller at remote://master:9999 -- java.nio.channels.UnresolvedAddressException
eapslave2_1   | [Host Controller] 23:33:42,086 WARN  [org.jboss.as.host.controller](Controller Boot Thread) JBAS016581: No domain controller discovery options remain.
eapslave2_1   | [Host Controller] 23:33:42,088 ERROR [org.jboss.as.host.controller](Controller Boot Thread) JBAS010901: Could not connect to master. Aborting. Error was: java.lang.IllegalStateException: JBAS016519: Tried all domain controller discovery option(s) but unable to connect
eapslave2_1   | [Host Controller] 23:33:42,097 INFO  [org.jboss.as](MSC service thread 1-15) JBAS015950: JBoss EAP 6.4.2.GA (AS 7.5.2.Final-redhat-2) stopped in 6ms
eapslave2_1   | [Host Controller] 
eapslave2_1   | 23:33:42,416 INFO  [org.jboss.as.process.Host Controller.status](reaper for Host Controller) JBAS012010: Process 'Host Controller' finished with an exit status of 99
eapslave2_1   | 23:33:42,417 INFO  [org.jboss.as.process](Thread-8) JBAS012016: Shutting down process controller
eapslave2_1   | 23:33:42,417 INFO  [org.jboss.as.process](Thread-8) JBAS012015: All processes finished; exiting
eapslave1_1   | RHQ Agent (pid 120 ) is ✔running
jbosseapmanagedondocker_eapslave1_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
Stopping jbosseapmanagedondocker_eapmaster_1... done
Stopping jbosseapmanagedondocker_jonserver_1... done
Stopping jbosseapmanagedondocker_eapslave2_1... done
Stopping jbosseapmanagedondocker_ewshttpd_1... done
Stopping jbosseapmanagedondocker_jonpostgres_1... done
Stopping jbosseapmanagedondocker_dnsmasq_1... done

**Comment by jgammon612** [comment]
cannot get any image to remain up -- docker-compose up always ends with containers above being stopped

**Comment by rafaeltuelho** [comment]
Hi @jgammon612 

Did you configured your RHEL 7's local firewall to accept/trust network traffic on `docker0` interface? 

I added a note on readme:

"NOTE: in RHEL like systems (Fedora or Centos) the Local Firewall runs by default. If this is your case, stop it or add a new rule to accept connections on docker0 interface for UDP PORT 53 (DNS). Our dnsmasq service binds to `docker0` (usually with 172.17.42.1 addr)."

In my case I used the graphical firewall configuration tool (hit `sudo firewall-config` in your shell console to open the tool) to apply this rule. See my screenshots:

![accept dns traffic](https://rafaeltuelho.files.wordpress.com/2015/10/rhel7-firewall-config-dns.png)
![trust on docker0 ifct](https://rafaeltuelho.files.wordpress.com/2015/10/rhel8-firewall-config-docker0-ifc.png)

**Comment by jgammon612** [comment]
the script is trying to connect to http://master:9999 when the correct port is 9990 -- how to fix -- also what is your iptables service doing -- is it enabled or not?

**Comment by jgammon612** [comment]
[Host Controller] 12:00:46,073 WARN  [org.jboss.as.host.controller](Controller Boot Thread) JBAS010900: Could not connect to remote domain controller at remote://master:9999 -- java.net.ConnectException: JBAS012174: Could not connect to remote://master:9999. The connection failed
eapslave2_1   | [Host Controller] 12:00:46,076 WARN  [org.jboss.as.host.controller](Controller Boot Thread) JBAS010900: Could not connect to remote domain controller at remote://master:9999 -- java.lang.IllegalStateException: JBAS010951: Could not connect to master in 8 attempts within 30000 ms
eapslave2_1   | [Host Controller] 12:00:46,076 WARN  [org.jboss.as.host.controller](Controller Boot Thread) JBAS016581: No domain controller discovery options remain.
eapslave2_1   | [Host Controller] 12:00:46,077 ERROR [org.jboss.as.host.controller](Controller Boot Thread) JBAS010901: Could not connect to master. Aborting. Error was: java.lang.IllegalStateException: JBAS016519: Tried all domain controller discovery option(s) but unable to connect

**Comment by jgammon612** [comment]
it works now - must have been firewalld

**Comment by jgammon612** [comment]
why do certain servers appear as unavailable? for example postgresql? I imported it and subs but it appears unavailable in jon

**Comment by jgammon612** [comment]
![serversshowingdown](https://cloud.githubusercontent.com/assets/14928349/10338128/cfaeb234-6cc9-11e5-8a32-cccaf998face.png)

**Comment by rafaeltuelho** [comment]
Hi!
We are almost there :-)

Yep! I will highlight a note about the Firewall config on README. By default the Docker engine uses `iptables` to setup inter-container network communication.

About the availability of resources imported to JON, maybe some issue with rhq-agent. 

See the logs on JON Server:
`docker-compose logs jonserver`

Access one of the containers and see the rhq-agent logs:

```
docker exec -ti jbosseapmanagedondocker_eapmaster_1 /bin/bash

[root@master /]# /opt/redhat/rhq-agent/bin/rhq-agent-wrapper.sh status
[root@master /]# tail -100f /opt/redhat/rhq-agent/logs/agent.log
```

try to restart the rhq-agent

```
/opt/redhat/rhq-agent/bin/rhq-agent-wrapper.sh restart
```

**Comment by rafaeltuelho** [comment]
News?

**Comment by jgammon612** [comment]
sorry -- other business to attend to

here is output -- looks like a simple credentials issue
[root@master /]#  /opt/redhat/rhq-agent/bin/rhq-agent-wrapper.sh status
rhq-agent-wrapper.sh: RHQ_AGENT_WRAPPER_BIN_DIR_PATH=/opt/redhat/rhq-agent/bin
rhq-agent-wrapper.sh: Loading environment script: /opt/redhat/rhq-agent/bin/rhq-agent-env.sh
rhq-agent-wrapper.sh: pidfile will be located at /opt/redhat/rhq-agent/bin/rhq-agent.pid
RHQ Agent                      (pid 71     ) is ✔running 

[root@master /]# tail -100f /opt/redhat/rhq-agent/logs/agent.log
<<<< abbreviated >>>>
org.rhq.core.pluginapi.inventory.InvalidPluginConfigurationException: Credentials for plugin to connect to AS7 management interface are invalid - update Connection Settings with valid credentials.
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:202)

so what are the agent credentials and where can I set?

**Comment by jgammon612** [comment]
also -- it would be nice if we can fix the fact that if I edit resolv.conf and add your your nameserver, it basically ignores some of my nameservers which I need. Is there some other way to set the resolv?

I really wish we had a very simple and easy network guide because that is mostly the issue here with docker. The docker network guide does not really cut it.

**Comment by rafaeltuelho** [comment]
> also -- it would be nice if we can fix the fact that if I edit resolv.conf and add your your nameserver, it basically ignores some of my nameservers which I need. Is there some other way to set the resolv?

hum, not really. Changing your `/etc/resolv.conf` is just a trick to access the services by name (apache, master, jon-server, etc). There is a limitation of 3 nameservers in `/etc/resolv.conf`. And this file is dynamically changed by the NetworkManager ever time you connect to a new network (eg: wifi or vpn).

> I really wish we had a very simple and easy network guide because that is mostly the issue here with docker. The docker network guide does not really cut it.

The network capabilities offered by Docker engine is limited to the Host. The inter-connection based on name resolution is very limited too (using links). Anything more complex depends on a Name Resolution service. The dnsmasq is the simpler way to deal with this scenario. But depending on your setup (like the one implemented here: many containers talking to each other) the maintenance becomes complicated.

The ideal in such setup (with many containers) is to use an Orchestration tool like: Kubernetes or Swarm. Unfortunately I didn't have time to use such orchestration solution yet.

**Comment by jgammon612** [comment]
what are the agent credentials?

**Comment by rafaeltuelho** [comment]
The agent uses a Token generated by the server the first time agent contacts the server. You can't change this token.

The log snippet above

> org.rhq.core.pluginapi.inventory.InvalidPluginConfigurationException: Credentials for plugin to connect to AS7 management interface are invalid - update Connection Settings with valid credentials.

Says the agent can't connect to the EAP instance. You have to manually inform the credentials used to access the EAP server instance. Go to the JON Console, access the resource (EAP server instance), `Inventory > Connection Settings` an change the username (`admin`) and password (`jboss@123`). Save and wait. After that the agent will start monitor the EAP instance.

**Comment by jgammon612** [comment]
so that worked for eap slave1 and slave 2 -- what should I do for the eap domain master?

**Comment by rafaeltuelho** [comment]
The same procedure should work for master too. Open the master platform,
select the JBoss Domain Controller resource, Inventory > Connection
Settings, change the username and password. Save and wait agent detect the
changes.

**Comment by jgammon612** [comment]
it did -- was just inpatient -- brought environment back up today and everything except postgresql was active -- speaking of which -- what is admin credential for postgresql (postgres/postgres?)?

----- Original Message -----

**Comment by rafaeltuelho** [comment]
Hi! good to know!

Well, I used the Postgres' Docker official image. It appears the postgres user password is generated during the image build. You can't know the original postgres credentials. One thing you can do is to access the postgres container shell and manually change the postgres password using `passwd` command.

**Comment by jgammon612** [comment]
haven't run the demo in a while and it once again won't start here is command line error (starting to get tiresome that what is supposed to help with configuration errors really doesn't):
docker-compose up -d
Starting jbosseapmanagedondocker_dnsmasq_1...
Cannot start container 18e4edba21471b2f166950a201ae15d64774de56fa26fbae4739bc1bc21c4cf5: Error starting userland proxy: listen udp 172.17.42.1:53: bind: cannot assign requested address

**Comment by jgammon612** [comment]
well - whatever I did worked. It is now back up and running. It would be nice however to have some means of verifying the environment. No idea what I did to fix which is scarier than anything

**Comment by rafaeltuelho** [comment]
Cool!
I will think on a way to check the setup. Maybe using a post start script.

**Comment by rafaeltuelho** [comment]
@jgammon612 ,

I made various tests in different environments (RHEL 7, Fedora 22 and Mac OS X). I suppose the root cause of the issues reported until now has to do with the proper firewall configuration that affects the `dnsmasq` service. 

I made some improvements on `README` instructions to highlight some points, prereqs and troubleshooting. I changed the `prepare.sh` also to check some prereqs.

If you have time and interest please give it a try! ;-)

Update you local repo:

```
git pull
```

and execute the `prepare.sh` script again to validate and rebuild the docker images used in our setup.

I will appreciate any feedback.
Thx.

**Comment by jgammon612** [comment]
Yea -- here are some notes that will help other users avoid some of the network problems:
I have started and stopped this project a hundred times successfully using this approach:
a) Start the docker service BEFORE adjusting firewall settings per above note;
b) make sure no iptables.service is running;
c) verify with docker ps that images are running and then edit resolv.conf by placing the nameserver 172.17.42.1 as the first entry below the "search aaa.bbb.com  ccc.ddd.net" 
d) give jon just a minute to establish connection to postgres and initalize
e) make sure the user running the agents on the slave images is same user who owns the install of the eap instance

I will definitely try out the additional post install scripts later!
